name: Validate Set JSON

on: [pull_request]

jobs:
  validate-set-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /.github/workflows/set-schema.json
          INPUT_JSONS: /sets.json
