name: Validate Card JSON

on: [pull_request]

jobs:
  validate-card-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /.github/workflows/card-schema.json
          INPUT_JSONS: /Dark.json,DarkLegacy.json,Light.json,LightLegacy.json
